//= =====================
// Auth Actions
//= =====================
export const AUTH_USER = 'AUTH_USER',
  UNAUTH_USER = 'UNAUTH_USER',
  GET_PROFILE = 'GET_PROFILE',
  AUTH_ERROR = 'AUTH_ERROR',
  FORGOT_PASSWORD_REQUEST = 'FORGOT_PASSWORD_REQUEST',
  RESEND_OTP = 'RESEND_OTP',
  RESET_PASSWORD_REQUEST = 'RESET_PASSWORD_REQUEST',
  PROTECTED_TEST = 'RESET_PASSWORD_REQUEST',
  REGISTER_USER = 'REGISTER_USER',
  VERIFY_OTP = 'VERIFY_OTP',
  FORGET_PASSWORD_REQUEST = 'FORGET_PASSWORD_REQUEST',
  CHANGE_PASSWORD_REQUEST = 'CHANGE_PASSWORD_REQUEST',
  REGISTER_GUEST_USER = 'REGISTER_GUEST_USER', 
  GET_ADDRESS = 'GET_ADDRESS',
  ADD_ADDRESS = 'ADD_ADDRESS',
  SEARCH_ADDRESS = 'SEARCH_ADDRESS',
  DELETE_ADDRESS = 'DELETE_ADDRESS',
  CHANGE_PREFERENCE_TAKE_ORDER_FROM_HOME = 'CHANGE_PREFERENCE_TAKE_ORDER_FROM_HOME',
  CHANGE_PREFERENCE_FREE_RECYCLING = 'CHANGE_PREFERENCE_FREE_RECYCLING',
  
  GUEST_VERIFY_OTP = 'GUEST_VERIFY_OTP',
  SEND_OTP_REQUEST_FORGET_PASSWORD ='SEND_OTP_REQUEST_FORGET_PASSWORD',
  RESEND_OTP_FORGET_PASSWORD ='RESEND_OTP_FORGET_PASSWORD',
  VERIFY_OTP_FORGET_PASSWORD ='VERIFY_OTP_FORGET_PASSWORD',
  RESET_PASSWORD_REQUEST_FORGET_PASSWORD ='RESET_PASSWORD_REQUEST_FORGET_PASSWORD';



  //= =====================
// User Barexchange 
//= =====================
export const BAREXCHANGES_CATEGORIES = 'BAREXCHANGES_CATEGORIES',
BAREXCHANGES_PRODUCTS = 'BAREXCHANGES_PRODUCTS',
BAREXCHANGES_PRODUCTS_ADD_TO_FAVOURATE = 'BAREXCHANGES_PRODUCTS_ADD_TO_FAVOURITE',
BAREXCHANGES_PRODUCTS_REMOVE_TO_FAVOURITE = 'BAREXCHANGES_PRODUCTS_REMOVE_TO_FAVOURITE',
BAREXCHANGES_PRODUCTS_LIST_FAVOURITE = 'BAREXCHANGES_PRODUCTS_LIST_FAVOURITE',
BAREXCHANGES_ERROR= 'BAREXCHANGES_ERROR';


//= =====================
// User Profile Actions
//= =====================
export const FETCH_USER = 'fetch_user',
    ERROR_RESPONSE = 'error_response';
    
    

//= =====================
// Home Page Actions
//= =====================
export const FETCH_BANNERS = 'FETCH_BANNERS',

  FETCH_BRANDS = 'FETCH_BRANDS',
  HOME_PAGE_PRODUCTS = 'HOME_PAGE_PRODUCTS',
  FETCH_ALL_BRANDS = 'FETCH_ALL_BRANDS',
  FETCH_BEST_SELLERS = 'FETCH_BEST_SELLERS',
  FETCH_CATEGORIES = 'FETCH_CATEGORIES',
  CATALOGUES_LIST = 'CATALOGUES_LIST',
  FETCH_CHILD_CATEGORIES = 'FETCH_CHILD_CATEGORIES',
  FETCH_ALL_CATEGORIES = 'FETCH_ALL_CATEGORIES', 
  CATEGORY_ERROR ="CATEGORY_ERROR",
  HOME_ERROR = 'HOME_ERROR';


//= =====================
// Ajax Actions
//= =====================
export const AJAX_REQUEST_PROCESSING = "AJAX_REQUEST_PROCESSING", 
    AJAX_REQUEST_COMPLETED = "AJAX_REQUEST_COMPLETED";  

//= =====================
// Common Actions
//= =====================
export const TOKEN_PREFIX = 'Bearer ';

//= =====================
// Product Const
//= =====================
export const FETCH_PRODUCT_DETAILS = 'FETCH_PRODUCT_DETAILS',
FETCH_PRODUCT_DETAILS_FOR_QUICK_VIEW = 'FETCH_PRODUCT_DETAILS_FOR_QUICK_VIEW',
    FETCH_COMBO_PRODUCT_DETAILS = 'FETCH_COMBO_PRODUCT_DETAILS',
    EMPTY_STATE = 'EMPTY_STATE',
    GET_PRODUCT_REVIEW = 'GET_PRODUCT_REVIEW',
    ADD_PRODUCT_REVIEW = 'ADD_PRODUCT_REVIEW',
    FETCH_PRODUCT_VARIANT_DETAILS = 'FETCH_PRODUCT_VARIANT_DETAILS',
    PRODUCT_ERROR   = 'PRODUCT_ERROR',
    FETCH_PRODUCTS  = 'FETCH_PRODUCTS',
    FETCH_PRODUCTS_SEARCH  = 'FETCH_PRODUCTS_SEARCH',
     FETCH_WISHLIST = 'FETCH_WISHLIST', 
     FETCH_CART_ITEMS       = 'FETCH_CART_ITEMS',
     FETCH_PRODUCT_FILTERS  = 'FETCH_PRODUCT_FILTERS',
     ADD_PRODUCT_TO_CART    = 'ADD_PRODUCT_TO_CART',
     UPDATE_CART    = 'UPDATE_CART',
     ADD_PRODUCT_TO_WISHLIST = 'ADD_PRODUCT_TO_WISHLIST', 
     REMOVE_CART_ITEM       = 'REMOVE_CART_ITEM',
     GET_CART_ITEMS       = 'GET_CART_ITEMS',
     GET_WISHLIST_ITEMS       = 'GET_WISHLIST_ITEMS',
     MOVE_CART_TO_WISHLIST  = 'MOVE_CART_TO_WISHLIST',
     MOVE_WISHLIST_TO_CART = 'MOVE_WISHLIST_TO_CART',
     REMOVE_WISHLIST_ITEM = 'REMOVE_WISHLIST_ITEM',
     FETCH_SIMILAR_PRODUCTS = 'FETCH_SIMILAR_PRODUCTS',
     TIME_SLOT = 'TIME_SLOT',
     FETCH_PRODUCTS_JUST_ARRIVED = 'FETCH_PRODUCTS_JUST_ARRIVED';



//= =====================
// Common Const
//= =====================
export const FETCH_COUNTRIES = 'FETCH_COUNTRIES',
    COMMON_ERRORS = 'COMMON_ERRORS',
    FETCH_STATES = 'FETCH_STATES',
    FETCH_CITIES = 'FETCH_CITIES',
    FETCH_AREAS = 'FETCH_AREAS',
    FETCH_WISHLIST_COUNT = 'FETCH_WISHLIST_COUNT', 
    FETCH_CART_COUNT = 'FETCH_CART_COUNT',
    FETCH_ZIPCODE = 'FETCH_ZIPCODE',
    GENERATE_OTP = 'GENERATE_OTP',
    FETCH_KEYWORD_SEARCH = 'FETCH_KEYWORD_SEARCH';


//= =====================
// MyAccount Const
//= =====================
export const FETCH_CUSTOMER_WALLET = 'FETCH_CUSTOMER_WALLET',
    CART_CHECKOUT = 'CART_CHECKOUT',
    CART_MAKE_PAYMENT = 'CART_MAKE_PAYMENT',
    FETCH_CUSTOMER_DETAILS = 'FETCH_CUSTOMER_DETAILS',
    CUSTOMER_ADD_ADDRESS = 'CUSTOMER_ADD_ADDRESS',
    CUSTOMER_REMOVE_ADDRESS = 'CUSTOMER_REMOVE_ADDRESS',
    CUSTOMER_UPDATE_ADDRESS = 'CUSTOMER_UPDATE_ADDRESS',
    UPDATE_PASSWORD = 'UPDATE_PASSWORD',
    CUSTOMER_ADD_EDIT_DLT_PHONE = 'CUSTOMER_ADD_EDIT_DLT_PHONE',
    ACCOUNT_ERRORS = 'ACCOUNT_ERRORS',
    CHANGE_EMAIL = 'CHANGE_EMAIL',
    CHANGE_ADD_PHONE = 'CHANGE_ADD_PHONE',
    CHANGE_PHONE_RESEND_OTP = 'CHANGE_PHONE_RESEND_OTP',
    CHANGE_PHONE = 'CHANGE_PHONE',
    CHANGE_NAME = 'CHANGE_NAME',
    VERIFY_CUSTOMER_PHONE = 'VERIFY_CUSTOMER_PHONE';


//= =====================
// Orders
//= =====================
export const FETCH_ORDERS = 'FETCH_ORDERS',
    ORDERS_PLACED = 'ORDERS_PLACED',
    FETCH_ORDER = "FETCH_ORDER", 
    RETURN_ORDERS = "RETURN_ORDERS",
    ORDERS_PRODUCT_REVIEW_RATING = "ORDERS_PRODUCT_REVIEW_RATING",
    CANCEL_ORDERS = "CANCEL_ORDERS",
    CANCEL_REASON = "CANCEL_REASON",
    ORDER_ERROR = 'ORDER_ERROR',
    OFFERS_AND_COUPONS = "OFFERS_AND_COUPONS",
    ORDER_PRODUCT_DETAILS = 'ORDER_PRODUCT_DETAILS',
    CANCEL_ORDER_PRODUCT = 'CANCEL_ORDER_PRODUCT',
    RETURN_ORDER_PRODUCT = 'RETURN_ORDER_PRODUCT';


//= =====================
// pages
//= =====================
export const SEND_CONTACT_REQUEST = 'SEND_CONTACT_REQUEST',
        PAGES_ERROR = 'PAGES_ERROR', 
        L_POINT = 'L_POINT',
        L_POINT_BOTEL_SELECT = 'L_POINT_BOTEL_SELECT',
        OFFER_PAGE = 'OFFER_PAGE',
        L_POINT_ERROR = 'L_POINT_ERROR', 
        CONTACT_US = 'CONTACT_US',
        HOME_HUB = 'HOME_HUB',
        PETITION = 'PETITION',
        SUBSCRIBE ='SUBSCRIBE',
        ECOAMBASSADOR = 'ECOAMBASSADOR',
        JUNIOR_ECO_AMBASSADOR = 'JUNIOR_ECO_AMBASSADOR'
        
        ;

//= =====================
// Servicessss
//= =====================
export const FETCH_SERVICES = 'FETCH_SERVICES', 
            SERVICES_ERROR = 'SERVICES_ERROR',
            FETCH_SERVICES_DETAILS = 'FETCH_SERVICES_DETAILS',
            FETCH_CORDINATES = 'FETCH_CORDINATES', 
            FETCH_COMMON_SERVICES_LIST = 'FETCH_COMMON_SERVICES_LIST',
            SEND_CONTACT_FROM ='SEND_CONTACT_FROM';


            
//============
// Customer support
//=============
export const FETCH_SUPPORT_TICKETS = 'FETCH_SUPPORT_TICKETS',
TICKET_DETAIL_BY_ID = 'TICKET_DETAIL_BY_ID', 
CSS_MESSAGE = 'CSS_MESSAGE', 
UPLOAD_FILE = 'UPLOAD_FILE', 
CLEAR_IMAGE_DATA = 'CLEAR_IMAGE_DATA', 
ERROR_IMAGE = 'ERROR_IMAGE', 
UPLOAD_IMAGE = 'UPLOAD_IMAGE', 
CSS_ERROR = 'CSS_ERROR',
CREATE_TICKET = 'CREATE_TICKET',
FETCH_ORDER_FOR_CCS = 'FETCH_ORDER_FOR_CCS',
FETCH_TICKET_TYPES = 'FETCH_TICKET_TYPES' ;