import React from 'react';
import { Link, browserHistory } from 'react-router';
import $ from "jquery";
class AboutUs extends React.Component {
  componentWillMount() {
    $("html, body").animate({ scrollTop: 0 }, 600);
  }
  redirectToLogin(event) {
    event.preventDefault();
    browserHistory.push({
        pathname: '/login',
        search: '',
        state: { previouspath:'/newin' }
       });
  }

    render(){
    
        
        return (

          
                <section id="section1" className="terms-and-conditions-sec content-sec p-b-50 m-t-50">{/*OPEN slider-sec */}
                  <div className="container">
                    <div className="about-sec-main">
                      <h2 className="inner-title">TERMS &amp; CONDITIONS</h2>
                      <h3 className="p-b-20">1. PURCHASE CONTRACT</h3>		  
                      <p><strong className="no">1.1 </strong>This website surreywhales.com is operated by Cacozi Limited ("we", "us" or "our"). Cacozi Limited is also referred to as Cacozi. By using the surreywhales.com website you are bound by these Terms &amp; Conditions. All use and purchases made on this website are governed by these Terms &amp; Conditions at any time although the Terms &amp; Conditions governing any given use or purchase will be those in effect at the date of your order or specific use. If you use or order goods after we have published any changes you will be bound by those changes. Accordingly, you should check prior to each use or order to ensure that you understand the precise Terms &amp; Conditions applicable to your site visit or purchase. To assist you in determining whether the Terms &amp; Conditions have changed since your most recent order we will display the date when these Terms &amp; Conditions were most recently updated.</p>
                      <p><strong className="no">1.2 </strong>We sell goods only to end-users.</p>
                      <p><strong className="no">1.3 </strong>We will confirm your order whether placed directly by using the surreywhales.com website. This will occur either by message on the website immediately after you have confirmed your order, or by us sending an e-mail to the e-mail address you have provided to us.</p>
                      <p><strong className="no">1.4 </strong>Please note that the order confirmation does not constitute our acceptance of your order. Subject to our cancellation rights in clause 11, acceptance of your order and completion of the contract will take place when we despatch the goods to you.</p>
                      <p><strong className="no">1.5 </strong>After confirmation of the order, any items added before the cut-off time will automatically form part of that order.</p>
                      <p><strong className="no">1.6 </strong>Any orders placed may be amended or cancelled by the customer at no charge, provided that this is done before the cut-off time stated on the order confirmation email or if none, as set out in clause 6 below. Any orders that have not been cancelled by this cut-off time are binding, and will be delivered by Surrey whales as set out in clause 1.3.</p>
                      <p><strong className="no">1.7 </strong>You must be 18 years old or over and must have completed the registration process in order to participate in our service.</p>
                      <h3 className="p-t-20 p-b-20">2. PRICE AND DELIVERY AND PLASTIC BAG CHARGES</h3>
                      <p><strong className="no">2.1a </strong>With the exception of goods referred to in clauses 2.1(b) and 2.1(c), but including goods from our butcher and fishmonger that are sold and priced by each (i.e. a fixed price per item) and packaged by us (as further identified on the website), the price of such goods will be as quoted on the website at the time you confirm your order (usually by clicking the "checkout" button) subject only to any inadvertent technical error for which we will not be liable. If you subsequently amend your order to add items, the prices charged for new products which were not in your original order will be the prices quoted at the time you confirm your amended order. However, if you add more of the same items which were in your original order, then the prices charged for these items will be the prices quoted at the time you confirmed your original order. Where a substitute item is offered in place of an item ordered, the price charged for that substitute item (if accepted) will be the price applicable at the time the item is substituted. Please note that as promotions are offered for a limited period of time subsequent amendments to your order may mean that certain promotions are no longer being offered.</p>
                      <p><strong className="no">2.1b </strong>Where items are ordered and sold individually by weight (such as certain fresh meat, poultry, fish, cheese or fruit and vegetables, but excluding “goods from our Butcher and Fishmonger” (see below) the price of these items (expressed per kilogram or other appropriate unit of measurement) will be the price on the date that they are weighed by our supplier. Although we have an indicative price/kg guide and an indicative product weight guide on the website, this is merely to assist your planning and the price you will be charged is the price prevailing on the date of weighing for the actual weight you receive. In the event that there is a discrepancy between the price/kg on our website at time your order is made and the price/kg at the time the item is weighed by our supplier, the price you will be charged will be the price at the time the item is weighed by our supplier. As used in this paragraph, “goods from our Butcher and Fishmonger” are goods that are individually packaged by us rather than by our suppliers, and either sold and priced individually by weight or sold and priced by item (as further identified on the website).</p>
                      <p><strong className="no">2.1c </strong>For goods from our Butcher and Fishmonger (as further identified on the website), the price of these items (expressed per kilogram or other appropriate unit of measurement) will be the price as quoted on the website at the time you confirm your order (usually by clicking the "checkout" button) subject only to any inadvertent technical error for which we will not be liable. If you subsequently amend your order to add items, the prices charged will be those applicable to the new item(s) at the time that the amended order is confirmed. Although we have an indicative weight guide on the website, this is merely to assist your planning and the price you will be charged is the price for the actual weight you receive. In the event that there is a change in the price/kg between the time you confirmed your order and the time the item is weighed and priced by us, the price you will be charged will be the price at the time you confirmed your order.</p>
                      <p><strong className="no">2.2 </strong>The prices stated on the website will be inclusive of any VAT payable.</p>
                      <p><strong className="no">2.3 </strong>Each order you make may include a charge for delivery. If your delivery is subject to a delivery charge, it will be shown to you as a separate charge on the delivery confirmation page before you confirm your order. Any delivery charge added to your order will be dependent upon, amongst other things, the value of your order, the date and time of your delivery and your delivery address and charges may vary from week to week.</p>
                      <p><strong className="no">2.4 </strong>There is a minimum order requirement of £30 (excluding delivery charges) for every order placed. The £30 minimum spend does not apply during the Christmas period, whereby the minimum order requirement will be £60 (excluding delivery charges). The Christmas delivery period is from 20 December to 24 December inclusive. The Christmas delivery charges will be the charges applicable at the time (as determined by Cacozi in its sole discretion).</p>
                      <p><strong className="no">2.5 </strong>The government introduced a charge for plastic bags in 2015, which means that by law we have to charge you. We will automatically charge you 10p for each plastic bag used for your delivery, but if you give your used plastic bags back to our driver for us to recycle, we will reimburse you 5p for each plastic bag returned.</p>
                      <h3 className="p-t-20 p-b-20">3. METHODS OF PAYMENT</h3>
                      <p><strong className="no">3.1 </strong>Payment may be made by debit, credit or charge card and some business account cards, as well as via PayPal. We also accept payment by Cacozi/Surrey whale Vouchers. No other vouchers or "money off" coupons will be accepted towards payment of an order. Any refunds arising from an order paid for by vouchers shall be given in Ocado vouchers. You cannot pay for your order by cash or cheque.</p>
                      <p><strong className="no">3.2 </strong>The debit, credit and charge cards accepted by us are those listed on the web site on the date on which your order is placed.</p>
                      <p><strong className="no">3.3 </strong>Authority for payment will be requested from your card issuer between the time of your order being placed and when it is delivered. This is done by 'reserving' against the card you have used for payment. The amount that is ‘reserved’ will either be the estimated amount of your order, including charges for carrier bags, or £1. That amount is not spent by you until we 'debit' your card with the full price of your order, and the latter happens after we have delivered your shopping to you. We reserve the right to cancel your order if we are refused authority for payment or reasonably believe that payment will be refused at any stage.</p>
                      <p><strong className="no">3.4 </strong>You agree to compensate us in full against all reasonable costs expenses and outgoings incurred by us in obtaining payments from you in the event a failed payment occurs. This may include an administration charge of not less than £20. We may at any time after a failed payment has occurred ask a debt collection agency to collect payment from you.</p>
                      <h3 className="p-t-20 p-b-20">4. DELIVERY</h3>
                      <p><strong className="no">4.1 </strong>Delivery days and times will be as specified on the delivery booking page on the website and will be made to the address specified by you when you register on the website. You have the ability to change this address through the "Details &amp; Settings" featured on the website, and you must do so if you move home so that we can deliver to the correct address. We reserve the right to restrict deliveries in certain areas, and this includes the right to eliminate certain areas from our delivery schedule altogether.</p>
                      <p><strong className="no">4.2 </strong>Products are subject to availability and prevailing market conditions. We may limit the quantities of goods (particularly goods on special offer) supplied to any one customer if in our opinion the quantity ordered jeopardises availability for other customers. In the event of non-availability of any goods you order, we may offer a reasonable substitute. This may affect the price you pay. You may reject any substitute item and we will refund the amount you have been charged for that substitute. It is our policy to identify any substitute items to you at the time of delivery and give you the opportunity to accept or reject the item at that time.</p>
                      <p><strong className="no">4.3 </strong>We will always try to supply you with the full quantity that you have ordered. If you are not satisfied with the quantity you have received we will arrange with you for non-perishable goods to be returned to us (please note that the goods must not be used and must be in good condition). In the event that the goods delivered to you are incomplete or include incorrect goods, you must notify us promptly. You will not be charged for any incorrect goods or goods which you have not received. In any event, subject to clause 7.1 below, our liability will be limited to the price of the goods not delivered or incorrectly delivered and the cost of delivery.</p>
                      <p><strong className="no">4.4 </strong>We take special care to endeavour that deliveries are made the next day and accordingly, it is your responsibility to ensure that an appropriate person is available at the delivery address at all times during the delivery slot. We may ask that an appropriate person signs for the goods on delivery. If no one is at the address when the delivery is attempted the goods will be retained by us. We will leave notification of delivery and will telephone to attempt to rearrange the delivery.</p>
                      <p><strong className="no">4.5 </strong>Please note adverse weather conditions or other events outside of our reasonable control may result in the occasional late or cancelled delivery. If that is the case we will endeavour to contact you as soon as we are able to in order to reschedule your delivery time and date. In any event, subject to clause 7.1 below, our liability to you will be limited to the price of goods not delivered and the cost of delivery.</p>
                      <p><strong className="no">4.6 </strong>Should you fail to be present for your delivery we are entitled to charge you in full for an amount equal to the price of perishable items contained in your order and the cost of delivery.</p>
                      <p><strong className="no">4.7 </strong>Cacozi will ordinarily only make deliveries when an appropriate person is able to receive the delivery. In the event that you instruct Cacozi to leave a delivery unattended at your address Cacozi expressly disclaims all liability which may arise by virtue of the delivery being left unattended for a period of time. This includes but is not limited to theft, tampering, contamination and the result of any change in temperature in respect of items which need to be kept chilled or frozen.</p>
                      <p><strong className="no">4.8 </strong>Deliveries are limited to one delivery per day per household.</p>
                      <h3 className="p-t-20 p-b-20">5. DEFECTIVE GOODS</h3>
                      <p><strong className="no">5.1 </strong>We advise that you inspect the goods promptly at the time of delivery and notify us of any defects promptly after delivery. If you discover a product is faulty, please call our Customer Service team as soon as possible on 0203 8088 336 or email contact@surreywhales.com. If you've received an order in the last 48 hours, you can request a refund through our website or app. Simply select the 'Request refund' link from the Orders page and follow the instructions. If more than 48 hours have passed and you don't see the 'Request refund' link, please email us at contact@surreywhales.com or call us on 0203 8088 336. We will arrange with you for the goods to be returned to us. On receipt of the goods, we will promptly and fully refund the price of any goods that do not meet with your reasonable satisfaction or arrange for the delivery of replacement goods.</p>
                      <p><strong className="no">5.2 </strong>As a consumer, you have certain legal rights regarding the return of faulty or misdescribed goods. Our refund procedure described above does not affect your legal rights in relation to such goods. Our returns policy is in accordance with statutory rights under the Consumer Contracts Regulations. For further information about your legal rights contact your local authority Trading Standards Department, or Citizens Advice.</p>
                      <h3 className="p-t-20 p-b-20">6. AMENDMENT OF ORDERS AND CANCELLATION RIGHTS</h3>
                      <p><strong className="no">6.1 </strong>The confirmation e-mail you receive from us confirming your order will set out the last time that, you may amend your order prior to delivery.</p>
                      <p><strong className="no">6.2 </strong>In respect of non-perishable items, you have the right to cancel the contract at any time until the expiry of the 14th working day after the date of delivery of the goods by notifying us by telephone or e-mail. We ask that items are returned in to us with their original packaging and with any tags intact. In the case of items which include a hygiene or security seal, we ask that you exercise reasonable care by not removing the seals while examining the goods, unless you are certain that you intend to keep the goods. In the event that any seals or tags are removed or tampered with, we shall not permit that item to be returned nor shall we refund the cost of this item to you.</p>	
                      <p><strong className="no">6.3 </strong>In the case of perishable items you do not have the right to cancel the contract. Should you wish to cancel your order after the cut off period but prior to the time of delivery, we shall be entitled to charge you in full for an amount equal to the price of the perishable items contained in your order.</p>	
                      <p><strong className="no">6.4 </strong>We will arrange with you for cancelled non-perishable goods to be returned to us, and we will credit your payment card with the price of such goods within 30 days from the date you returned the goods to us (provided payment has already been debited to your payment card). If you choose to return goods by post you will be responsible for the cost of postage.</p>	
                      <h3 className="p-t-20 p-b-20">7. WARRANTY AND LIABILITY</h3>
                      <p><strong className="no">7.1 </strong>Nothing in these Terms &amp; Conditions will restrict our liability for death or personal injury resulting from our negligence, breach of contract or breach of statutory duty, nor will any of these terms restrict any of your statutory rights. For further information about your statutory rights, contact your local authority Trading Standards Department or Citizen's Advice Bureau.</p>
                      <p><strong className="no">7.2 </strong>In addition to paragraph 4.4, we will not be deemed to be in breach of contract or of these Terms &amp; Conditions as a result of any delay in our performance or failure to perform our obligations if that delay or failure to perform is due to any cause or circumstance beyond our reasonable control including, but not limited to, fire, flood and other acts of God, strikes, riot, accident, disruption to energy supplies, civil commotion, acts of terrorism or war, breakdown of equipment, road traffic problems.</p>	
                      <p><strong className="no">7.3 </strong>Other than as set out in clause 7.1, our maximum liability arising out of any order for the supply of goods to you under this contract will be limited to the retail price of the goods contained in that order.</p>
                      <h3 className="p-t-20 p-b-20">8. PRIVACY</h3>
                      <p><strong className="no">8.1 </strong>Telephone calls made to and from our Customer Service team are recorded for quality and monitoring purposes.</p>
                      <p><strong className="no">8.2 </strong>In assessing your request for delivery of groceries from us we may make enquiries about you including searching your records held by organisations like Experian and Equifax and credit reference agencies. We may also check your details held by the IMRG Security Alert scheme and other fraud prevention schemes.</p>	
                      <p><strong className="no">8.3 </strong>We respect your privacy. The personal information that you give us is held with care and security. We do not sell, rent or transfer this information to third parties for their marketing purposes unless you agree otherwise. We will share your personal information with other businesses operated by members of the Cacozi Limited provided that they follow practices at least as protective as those described in the Cacozi privacy policy.</p>	
                      <p><strong className="no">8.4 </strong>Please keep your password secret, as you are entirely responsible if you do not maintain the confidentiality of your password. You are entirely responsible for all orders placed with us or information given to us under your e-mail address in combination with your password. You must immediately notify us of any unauthorised use of your e-mail address and/or password or any breach of security known to you.</p>	
                      <h3 className="p-t-20 p-b-20">9. CUSTOMER COMPLAINTS</h3>
                      <p><strong className="no">9.1 </strong>Any Customer complaints should be addressed to the Surrey whales Customer Service Helpline  you will find an e-mail link or address and telephone numbers listed on our website in the "Contact" section.</p>
                      <h3 className="p-t-20 p-b-20">10. SPECIAL OFFERS PROMOTIONS AND COMPETITIONS</h3>
                      <p><strong className="no">10.1 </strong>From time to time, and in our complete discretion, purchases of goods may be subject to special offers. In the event that such a special offer applies to your purchase, the terms of such special offer shall be subject to these Terms &amp; Conditions. If there is any conflict between the terms of a special offer and these Terms &amp; Conditions, these Terms &amp; Conditions shall prevail unless specifically excluded.</p>	
                      <p><strong className="no">10.2 </strong>We may change the terms of special offers, or withdraw them altogether, at any time and without prior notice. Subject to clauses 2.1(a) and 4.2, we will honour at the offer price any order placed by you before an offer ends, or is amended or withdrawn.</p>	
                      <p><strong className="no">10.3 </strong>We reserve the right to offer in our complete discretion different customers different special offers, promotions and the ability to enter different competitions.</p>	
                      <h3 className="p-t-20 p-b-20">11. CANCELLATION OF DELIVERIES AND SUSPENSION OF YOUR ACCOUNT</h3>
                      <p><strong className="no">11.1 </strong>We reserve the right to cancel your delivery at any time if we suspect fraud, have reason to believe you are in breach of these Terms and Conditions or any other terms and conditions relating to your order, or if there is an outstanding payment for any account registered at your address. In the event that we cancel your order, you will receive email notification and will be invited to contact our call centre on 0203 8088 336.</p>
                      <p><strong className="no">11.2 </strong>In addition to our right to cancel your order in accordance with clause 11.1 , we reserve the right to suspend your account. Your account will remain suspended until you contact our call centre on 0203 8088 336 and remedy any breaches which are capable of remedy, or provide any information reasonably requested by our call centre advisers to enable them to reactivate your account.</p>
                      <p><strong className="no">11.3 </strong>In the rare event that unforeseen operational or technical issues occur, we may need to cancel or rearrange delivery. If this happens we will endeavour to contact you to arrange an alternative delivery date.</p>
                      <h3 className="p-t-20 p-b-20">12. GENERAL</h3>
                      <p><strong className="no">12.1 </strong>If any of these Terms &amp; Conditions is held by any court of competent authority to be unlawful, invalid or unenforceable, in whole or in part, this will not affect the validity of the remaining Terms &amp; Conditions which will continue to be valid and enforceable to the fullest extent permitted by law.</p>
                      <p><strong className="no">12.2 </strong>All copyright, trademarks and all other intellectual property rights in all material or content supplied as part of this website shall remain at all times vested in us or our licensors. You are permitted to use the material data and content only for your personal use in placing orders through surreywhales.com, and you may not otherwise copy, reproduce, transmit, publish, display, distribute, commercially exploit, use or create derivative works of any material data and content on the surreywhales.com website without Cacozi's prior written permission. Cacozi may impose a fee on any proposed use of the material data and content contained on its website, other than for placing orders through the surreywhales.com website.</p>
                      <p><strong className="no">12.3 </strong>These Terms &amp; Conditions will be governed by English law and the parties submit to the exclusive jurisdiction of the English courts in relation to any dispute which may arise between them.</p>
                      <p><strong className="no">12.4 </strong>Surreywhales.com is a trading name of Cacozi Limited. The registered company address for Cacozi Limited is 27 Old Gloucester road, London, WC1N 3AX. Registered in England. Company registration number: 11150929</p>
                    </div>
                  </div>
                </section>
        );
    }
}




export default(AboutUs);